# Magic function in Jupyter Notebook

In [3]:
print("Hello World")
print("AI")
print("DS")


Hello World
AI
DS


In [4]:
%history


%history
print("Hello World")
print("Hello World")
print("AI")
print("DS")
%history


In [ ]:
# %load maths.py
def add(a,b):
    return a + b

def subtract(a,b):
    return a - b

def multiply(a,b):
    return a * b

def divide(a,b):
    return a / b

In [8]:
%run readWrite.py

A.Wahab


In [12]:
%time print("AI Engineer")

AI Engineer
Wall time: 0 ns


# Python

In [17]:
%time l = list(range(100000))
print(l[1:11])

Wall time: 5 ms
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [18]:
%time l = [x+5 for x in l]
print(l[1:11])

Wall time: 10 ms
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [20]:
for i,e in list(enumerate(l)):
    l[i] += 5
print(l[1:11])

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [21]:
l1 = [[1,2,3], [4,5,6], [7,8,9]]
for ri, re in list(enumerate(l1)):
    for ci,ce in list(enumerate(re)):
        l1[ri][ci] += 5
print(l1)

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


# Numpy

In [33]:
l= list(range(5000000))
%time for i in range(1,11): r=[x*2 for x in l]
print(r[:10])

Wall time: 5.75 s
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [38]:
import numpy as np
a = np.arange(5000000)
%time for i in range(1,11): d= a*2
print(d[:9])

Wall time: 147 ms
[ 0  2  4  6  8 10 12 14 16]


# Multidimentional Array Object

In [40]:
l1 = np.arange(1,13)
print("Dimension : ", l1.ndim)
print("Size : ", l1.size)
print("Item size : ", l1.itemsize)
print("Shape : ", l1.shape)
print("Data Type : ", l1.dtype)

Dimension :  1
Size :  12
Item size :  4
Shape :  (12,)
Data Type :  int32


In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.empty((3,6))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.11393730e-307, 4.00540117e-307, 8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307, 7.56594375e-307, 6.23060065e-307],
       [1.78021527e-306, 8.34454050e-308, 1.11261027e-306,
        1.15706896e-306, 1.33512173e-306, 1.42404727e-306]])

In [50]:
l = [1,2,3,4,5]
np.array(l)


array([1, 2, 3, 4, 5])

In [56]:
x = np.arange(0,101,10)


In [57]:
x.shape

(11,)

In [62]:
y= np.zeros((10,10))

In [63]:
y.shape

(10, 10)

In [75]:
x = y.reshape(2,2,5,5)

In [76]:
x.dtype



dtype('float64')

In [77]:
x.ndim


4

In [78]:
x.size

100

In [79]:
y.itemsize

8

In [81]:
y.shape

(10, 10)

In [87]:
l1 = np.arange(1,13)

In [88]:
l1.shape

(12,)

In [89]:
l1.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [99]:
l1 = np.arange(1,28).reshape(3,3,3)
print(l1)
l1[2,1,2]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


24

In [101]:
l2 = np.arange(1,28).reshape(3,3,3)
print(l1)
l2[l2 % 3 == 0]



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [107]:
x = np.random.randn(3,3,3)
x

array([[[ 0.28712356,  0.83721288,  0.65991718],
        [ 0.51846439,  0.36673298,  1.10840873],
        [ 2.4281465 , -0.21900839, -0.31192844]],

       [[ 0.05147036,  2.23231711,  0.58128139],
        [-0.1545097 , -0.68067196,  0.29562367],
        [ 0.24812985,  1.8244735 ,  0.16513061]],

       [[-0.84328262,  0.44259541, -0.68790152],
        [ 1.18080544, -0.84635118,  0.55628794],
        [ 0.76002839,  0.14076916, -1.99714164]]])

In [108]:
print("Data Type : ",x.dtype)
print("Shape : ",x.shape)
print("Item Size : ",x.itemsize)
print("Size : ",x.size)
print("Dimension : ",x.ndim)

Data Type :  float64
Shape :  (3, 3, 3)
Item Size :  8
Size :  27
Dimension :  3


In [26]:
l = [1,2,3]
a= np.array(l)
b= np.array(a)
print(a is l)
print(b is a)

False
False


In [33]:
l = [1,2,3,4,5]
a = np.asarray(l)
b = np.asarray(a)
c = np.asarray(b, dtype=np.float64)
print(a is l)
print(b is a)
print(c is b)


False
True
False


In [34]:
a = np.matrix(np.ones((3,3)))
a

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [36]:
np.array(a)[2]=2
a

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [37]:
np.asarray(a)[2]=2
a

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.]])

In [48]:
a = np.random.randn(9).reshape(3,3)
a

array([[-0.28134346,  0.69813524,  1.25124123],
       [-0.63082823, -0.55310282,  1.1845222 ],
       [-0.62383902, -1.2833294 , -2.45347889]])

In [47]:
b = np.random.randn(9).reshape(3,3)
b

array([[ 0.2733208 , -0.23010293,  0.31571414],
       [ 0.16581989,  1.25177158, -0.29194826],
       [ 0.66294637,  0.36465115,  0.26400662]])

In [49]:
a*b

array([[-0.07689702, -0.16064296,  0.39503454],
       [-0.10460387, -0.69235839, -0.34581919],
       [-0.41357181, -0.46796754, -0.64773468]])

In [50]:
a*2

array([[-0.56268692,  1.39627048,  2.50248246],
       [-1.26165647, -1.10620564,  2.3690444 ],
       [-1.24767803, -2.56665881, -4.90695778]])

In [51]:
1/a

array([[-3.55437442,  1.43238723,  0.7992064 ],
       [-1.58521757, -1.8079821 ,  0.84422225],
       [-1.60297765, -0.77922317, -0.40758451]])

In [52]:
a**2


array([[0.07915414, 0.48739281, 1.56560461],
       [0.39794426, 0.30592273, 1.40309285],
       [0.38917512, 1.64693436, 6.01955866]])

In [54]:
b[b>0]

array([0.2733208 , 0.31571414, 0.16581989, 1.25177158, 0.66294637,
       0.36465115, 0.26400662])

In [61]:
x= np.array([1,5,3,9,0,4])
x[1]


5

In [62]:
x[x>5]                      #boolean indexing

array([9])

In [64]:
x = np.random.randn(10,10)
x

array([[-0.06430345, -1.11623516, -0.69546874,  1.76551352,  1.92238047,
         0.1933133 , -0.97433263,  1.16341514,  0.53201931,  0.06124025],
       [ 0.02494188, -0.66708396,  0.70877352, -0.25142017,  1.12357359,
        -0.10063819,  0.67384003,  0.22515281, -0.68223579, -0.47194668],
       [-1.45218331, -0.96095569,  1.93689641,  1.95096477, -0.51837147,
         0.71112416, -1.39712354,  0.5730639 ,  0.1675583 ,  0.7144889 ],
       [-0.89069455, -0.83810065,  3.12426588,  0.10392708, -0.10413527,
        -0.80827753,  0.81078212,  3.31694909, -1.51714821,  0.17651163],
       [ 0.26153632, -0.57450678,  0.69623884, -0.18631179,  0.06754659,
         0.06883653,  0.02692133,  1.49214167,  0.42377154,  1.52774754],
       [ 0.15302248,  0.33146087,  1.13444549, -0.67747538,  1.13287903,
         0.53325612, -0.67259469, -0.83814105, -0.66703045, -0.4733042 ],
       [ 0.21752468, -1.64921016, -2.55044433,  0.82661716, -0.4142447 ,
         0.96523829,  0.3760633 , -0.4309474 

In [65]:
x[0][4]

1.9223804710739876

In [66]:
x[0:11:2]

array([[-0.06430345, -1.11623516, -0.69546874,  1.76551352,  1.92238047,
         0.1933133 , -0.97433263,  1.16341514,  0.53201931,  0.06124025],
       [-1.45218331, -0.96095569,  1.93689641,  1.95096477, -0.51837147,
         0.71112416, -1.39712354,  0.5730639 ,  0.1675583 ,  0.7144889 ],
       [ 0.26153632, -0.57450678,  0.69623884, -0.18631179,  0.06754659,
         0.06883653,  0.02692133,  1.49214167,  0.42377154,  1.52774754],
       [ 0.21752468, -1.64921016, -2.55044433,  0.82661716, -0.4142447 ,
         0.96523829,  0.3760633 , -0.4309474 , -1.18610146,  0.98920476],
       [ 0.32031511,  1.34848551,  1.06180098, -1.90799123,  0.56077427,
         0.60136333,  0.4851582 , -0.93941789,  0.05225956, -1.6928764 ]])

In [67]:
x[::,0:5]

array([[-0.06430345, -1.11623516, -0.69546874,  1.76551352,  1.92238047],
       [ 0.02494188, -0.66708396,  0.70877352, -0.25142017,  1.12357359],
       [-1.45218331, -0.96095569,  1.93689641,  1.95096477, -0.51837147],
       [-0.89069455, -0.83810065,  3.12426588,  0.10392708, -0.10413527],
       [ 0.26153632, -0.57450678,  0.69623884, -0.18631179,  0.06754659],
       [ 0.15302248,  0.33146087,  1.13444549, -0.67747538,  1.13287903],
       [ 0.21752468, -1.64921016, -2.55044433,  0.82661716, -0.4142447 ],
       [-1.46960734, -2.68502527, -0.06763034, -0.62167877,  0.53990097],
       [ 0.32031511,  1.34848551,  1.06180098, -1.90799123,  0.56077427],
       [ 1.22393576, -0.7649137 , -0.10257697, -0.99800756, -0.5790817 ]])

In [69]:
y = np.ones((5,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
y[1:-1, 1:-1]=0
y

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [86]:
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
x[0:-1,0:-1]=1
x

array([[1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# Array function

In [2]:
import numpy as np
x = np.array([1,7,4,9,11])
np.sqrt(x)

array([1.        , 2.64575131, 2.        , 3.        , 3.31662479])

In [3]:
np.power(x,2)

array([  1,  49,  16,  81, 121], dtype=int32)

In [6]:
y = np.array([9,4,1,2,8])
np.maximum(x,y)

array([ 9,  7,  4,  9, 11])

# Where


In [10]:
salary = np.array([0,50000,-232,100000])
np.where(salary<=0,1000,salary)


array([  1000,  50000,   1000, 100000])

In [11]:
salary = np.array([30000,-342342,60000,0])
np.where(salary<=0,"Not Ok","Ok")

array(['Ok', 'Not Ok', 'Ok', 'Not Ok'], dtype='<U6')

# Mathmatical and statistical Methods

In [12]:
x = np.array([1,7,4,2,11])
x


array([ 1,  7,  4,  2, 11])

In [13]:
x.mean()


5.0

In [15]:
x.cumsum()

array([ 1,  8, 12, 14, 25], dtype=int32)

In [16]:
x.cumprod()

array([  1,   7,  28,  56, 616], dtype=int32)

In [19]:
y = x>3
y

array([False,  True,  True, False,  True])

In [21]:
y.sum()

3

In [23]:
y.any()

True

In [24]:
y.all()

False

In [26]:
x = np.array([1,3,4,3,5,5,6,1])

array([ 1,  2,  4,  7, 11])

In [27]:
np.unique(x)

array([ 1,  2,  4,  7, 11])

In [28]:
np.sort(x)

array([ 1,  2,  4,  7, 11])

# File Input Output

In [29]:
x = np.array([1,2,3,4,5])


In [30]:
y = np.array([6,7,8,9,10])

In [31]:
np.save("Testx",x)

In [36]:
loadx = np.load("Testx.npy")

In [37]:
loadx

array([1, 2, 3, 4, 5])

In [51]:
np.savez("Testxy",x=x,y=y)


In [52]:
loadxy = np.load("Testxy.npz")

In [53]:
loadxy['y']

array([ 6,  7,  8,  9, 10])

In [54]:
loadxy['x']

array([1, 2, 3, 4, 5])

# Linear Algebra Functions

In [60]:
x = np.random.randn(3,3)
x

array([[-0.1031273 , -0.88398957, -1.88907069],
       [-0.64874439, -0.73598436,  0.45608915],
       [-0.08720199,  0.09030801,  0.33978834]])

In [64]:
x.diagonal()



array([-0.1031273 , -0.73598436,  0.33978834])

In [67]:
x.trace()

-0.4993233209189617

In [68]:
y = np.random.randn(3,3)
y


array([[ 0.52030318,  0.76373405, -0.73352015],
       [-0.52409618,  0.8382641 ,  0.74729951],
       [-0.27398525, -0.76070808,  1.67732366]])

In [70]:
x.dot(y)

array([[ 0.9272156 ,  0.61725278, -3.75354198],
       [-0.07677887, -1.45936816,  0.69087545],
       [-0.18579855, -0.24937691,  0.70138656]])

In [71]:
y.transpose()

array([[ 0.52030318, -0.52409618, -0.27398525],
       [ 0.76373405,  0.8382641 , -0.76070808],
       [-0.73352015,  0.74729951,  1.67732366]])

# Chaining

In [4]:
def A(x): return x+5
def B(x): return x+6
def C(x): return x+7

In [5]:
C(B(A(1)))

19

In [6]:
A(B(C(2)))

20

In [ ]:
np.A().B().C()

In [11]:
a= np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [13]:
a = np.reshape(np.arange(1,28), (3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [25]:
a = np.arange(1,28)
print(a)
print(a.ndim)
a.shape = (3,9)
print(a.ndim)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


In [16]:
a.shape = (3,9)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [28]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [29]:
a.shape

(9, 3)

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros(a.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
b = np.zeros_like(a) + 5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [43]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
c = np.ones_like(a)
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
c = np.ones_like(a) * 10
c

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [49]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [51]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [52]:
np.full_like(a,10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [53]:
np.full_like(a,2.5)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [57]:
np.full_like(a,2.5,dtype=np.float64)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [62]:
np.empty((3,9))

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [63]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [64]:
np.full(a.shape,np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [70]:
x=np.full_like(a,1) * np.nan
x

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Data Type

In [86]:
a = np.array([1,2,3,4],dtype="int")
a.dtype

dtype('int32')

In [87]:
a = np.array([1,2,3,4],dtype=int)
a.dtype

dtype('int32')

In [88]:
a = np.array([1,2,3,4],dtype=np.int64)
a.dtype

dtype('int64')

In [89]:
a = np.array([1,2,3,4],dtype="i8")
a.dtype

dtype('int64')

In [91]:
b = np.array([1,2,3,4],dtype=a.dtype)
b.dtype

dtype('int64')

In [94]:
c = b.astype(np.float64)
c.dtype

dtype('float64')

# Boolean Operation

In [97]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [98]:
a% 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [101]:
print(a)
a[a%3 == 0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [111]:
print(a)
a[(a%3 == 0) & (a%5 ==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [112]:
a[~(a%3 == 0)]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [113]:
a[a%3!=0]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

# Random Number

In [8]:
import numpy as np
np.random.seed(5)

In [9]:
np.random.normal(size=(3,3))

array([[ 0.44122749, -0.33087015,  2.43077119],
       [-0.25209213,  0.10960984,  1.58248112],
       [-0.9092324 , -0.59163666,  0.18760323]])

In [11]:
np.random.uniform(size=(3,3))


array([[0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993],
       [0.62878791, 0.57983781, 0.5999292 ]])

# Reshape

In [34]:
x = np.random.randn(4,5)
x

array([[-0.92133518,  2.13266765, -0.38056226, -2.13080095,  0.69665506],
       [-0.10038772,  0.96878656,  1.84190347, -1.12735176,  0.56123214],
       [ 0.033073  , -0.01692838,  1.48055315,  0.47309345, -1.31421292],
       [ 0.83352633,  0.80978418, -1.77977907, -1.73799642, -1.06284807]])

In [35]:
x.reshape((2,2,5))

array([[[-0.92133518,  2.13266765, -0.38056226, -2.13080095,
          0.69665506],
        [-0.10038772,  0.96878656,  1.84190347, -1.12735176,
          0.56123214]],

       [[ 0.033073  , -0.01692838,  1.48055315,  0.47309345,
         -1.31421292],
        [ 0.83352633,  0.80978418, -1.77977907, -1.73799642,
         -1.06284807]]])

In [42]:
x.reshape((2,2,-1))

array([[[-0.92133518,  2.13266765, -0.38056226, -2.13080095,
          0.69665506],
        [-0.10038772,  0.96878656,  1.84190347, -1.12735176,
          0.56123214]],

       [[ 0.033073  , -0.01692838,  1.48055315,  0.47309345,
         -1.31421292],
        [ 0.83352633,  0.80978418, -1.77977907, -1.73799642,
         -1.06284807]]])

In [46]:
x.reshape((4,5), order='F')


array([[-0.92133518,  2.13266765, -0.38056226, -2.13080095,  0.69665506],
       [-0.10038772,  0.96878656,  1.84190347, -1.12735176,  0.56123214],
       [ 0.033073  , -0.01692838,  1.48055315,  0.47309345, -1.31421292],
       [ 0.83352633,  0.80978418, -1.77977907, -1.73799642, -1.06284807]])

In [39]:
x.flatten()

array([-0.92133518,  2.13266765, -0.38056226, -2.13080095,  0.69665506,
       -0.10038772,  0.96878656,  1.84190347, -1.12735176,  0.56123214,
        0.033073  , -0.01692838,  1.48055315,  0.47309345, -1.31421292,
        0.83352633,  0.80978418, -1.77977907, -1.73799642, -1.06284807])

# Concatenate

In [6]:
x = [[1,2,3],[4,5,6]]
y = [[7,8,9],[10,11,12]]

In [7]:
import numpy as np
arr1 = np.array(x)
arr2 = np.array(y)

In [11]:
np.concatenate((arr1,arr2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
np.concatenate((arr1,arr2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [15]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[11,22,33],[44,55,66],[77,88,99]]

In [21]:
arr3 = np.array(a)
arr4 = np.array(b)

In [22]:
np.vstack((arr3,arr4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [23]:
np.hstack((arr3,arr4))

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66],
       [ 7,  8,  9, 77, 88, 99]])

# Split

In [24]:
x = [1,2,3,4,5,6,7,8,9,10]

In [27]:
arr1 = np.array(x)
np.split(arr1,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10])]

In [40]:
y = [[1,2,3,4,5,11,22,33],[6,7,8,9,10,44,55,66]]
arr2 = np.array(y)
np.split(arr2,[3,6], axis=1)

[array([[1, 2, 3],
        [6, 7, 8]]), array([[ 4,  5, 11],
        [ 9, 10, 44]]), array([[22, 33],
        [55, 66]])]

In [49]:
y = [[1,2,3,4,5,11,22,33],[6,7,8,9,10,44,55,66]]
arr2 = np.array(y)
np.split(arr2,[1], axis=0)

[array([[ 1,  2,  3,  4,  5, 11, 22, 33]]),
 array([[ 6,  7,  8,  9, 10, 44, 55, 66]])]

In [51]:
y = [[1,2,3,4,5,11,22,33],[6,7,8,9,10,44,55,66]]
arr2 = np.array(y)
np.hsplit(arr2,[5])

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]), array([[11, 22, 33],
        [44, 55, 66]])]

In [53]:
y = [[1,2,3,4,5,11,22,33],[6,7,8,9,10,44,55,66]]
arr2 = np.array(y)
np.vsplit(arr2,[1])

[array([[ 1,  2,  3,  4,  5, 11, 22, 33]]),
 array([[ 6,  7,  8,  9, 10, 44, 55, 66]])]

# Repeat and Tile

In [56]:
x = [1,2,3,4,5]
arr = np.array(x)
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [57]:
np.tile(arr,3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])